"""
>> python the-workshop.py
"""
from lots_of_useful.things import *
from time import time

start_time = time()

def what_time_are_we_on():
    time_elapsed = time() - start_time
    print('\n(%s mins)' % (int(time_elapsed / 60)))

# let's begin !

print('\n')
print('Handle with care')
print('                /')
print('                caring for your exceptions')
print('\n')
print('By way of an introduction, and to start our relationship with empathy, we are going to try and understand python\'s limits, how we can communicate with it and what will does it not understand.')
raw_input('...')

new_page()
print('\n')
print('1. How do we interact with it?')
print('Today, in order to interact with python we will be PASSING things to python.')
print('python will try to READ what we pass to it, from beginning to end, if it understands it...')
print('if it does not understand it will let us know !')
print('\n')
print('python here-you-go.py')
what_time_are_we_on()
raw_input('...')

new_page()
print('\n')
print('2. What does it not understand')
print('There are 4 small exercises we are going to follow together, each of them will require us to "fix" something that python does not understand.')
print('Each of them should illustrate some small aspect about how python *tries* to understand us.')
print('\n')
print('We will also learn *how* python expresses what it does not understand and tries to help us understand.')
print('\n')
print('I will walk you through them all first and then it is over to you')
print('\n')
print('    * Structure')
print('      >> python introductions/1-structure.py')
print('    * Names')
print('      >> python introductions/2-names.py')
print('    * Arrangements')
print('      >> python introductions/3-arrangements.py')
print('    * Types and Attributes')
print('      >> python introductions/4-types-and-attributes.py')
what_time_are_we_on()
raw_input('...')

new_page()
print('\n')
print('The snake + the mouse')
print('\n')
print('Collaborating in our own words.')
print('Writing in our own voice.')
print('    * concrete poetry')
print('    * words in space')
print('    * random creations')
print('    * animated words')
print('\n')
print('We will have a quick walk-through of some examples of concrete poetry /artists practicing with text-based work')
print('>> python poetry-text-art-inspiration.py')
what_time_are_we_on()
raw_input('...')

new_page()
print('\n')
print('Now we will take a quick look at a few examples of what we can do with python and then we will write something of our own.')
print('\n')
print('    * Pacing & spacing')
print('      >> python a-portable-paradise.py')
print('    * Layout')
print('      >> python my-muddled-thoughts.py')
print('    * Time-based & to accompany something else')
print('      >> python bjork-talking-about-tv.py')
print('    * Absurd !')
print('      >> python have-you-been-working-on-anything-lately.py')
what_time_are_we_on()
raw_input('...')

new_page()
print('\n')
print('Your turn !')
print('\n')
print('I will show you how to create a file and then you can explore writing something simple yourself.')
print('I suggest an easy place to start is copy and pasting one of the examples below:')
print('\n')
print('    * python example-flashing-poem.py')
print('    * python example-spacing.py')
print('    * python example-spacing-and-pacing.py')
what_time_are_we_on()
raw_input('...')
